### ISSUE TITLE
Unable to build pypy 3.5 and 3.6

### ISSUE THREAD

**Issue by Bidski** [squeaky-pl/portable-pypy#41]
Attempting to build pypy from either of the py3.5 or py3.6 branches using the provided docker container fails with the following error.

```
[platform:Error] /src/usession-py3.5-0/platcheck_89.c: In function 'dump_section_EPOLL_CLOEXEC':
[platform:Error] /src/usession-py3.5-0/platcheck_89.c:270:7: error: 'EPOLL_CLOEXEC' undeclared (first use in this function)
[platform:Error]   if ((EPOLL_CLOEXEC) <= 0) {
[platform:Error]        ^~~~~~~~~~~~~
[platform:Error] /src/usession-py3.5-0/platcheck_89.c:270:7: note: each undeclared identifier is reported only once for each function it appears in
[translation:info] Error:
   File "/src/pypy/rpython/translator/goal/translate.py", line 284, in main
    default_goal='compile')
   File "/src/pypy/rpython/translator/driver.py", line 566, in from_targetspec
    spec = target(driver, args)
   File "pypy/goal/targetpypystandalone.py", line 330, in target
    return self.get_entry_point(config)
   File "pypy/goal/targetpypystandalone.py", line 361, in get_entry_point
    space = make_objspace(config)
   File "/src/pypy/pypy/tool/option.py", line 35, in make_objspace
    return Space(config)
   File "/src/pypy/pypy/interpreter/baseobjspace.py", line 432, in __init__
    self.initialize()
   File "/src/pypy/pypy/objspace/std/objspace.py", line 105, in initialize
    self.make_builtins()
   File "/src/pypy/pypy/interpreter/baseobjspace.py", line 617, in make_builtins
    self.install_mixedmodule(mixedname, installed_builtin_modules)
   File "/src/pypy/pypy/interpreter/baseobjspace.py", line 656, in install_mixedmodule
    modname = self.setbuiltinmodule(mixedname)
   File "/src/pypy/pypy/interpreter/baseobjspace.py", line 495, in setbuiltinmodule
    None, None, ["Module"]).Module
   File "/src/pypy/pypy/module/select/__init__.py", line 8, in <module>
    class Module(MixedModule):
   File "/src/pypy/pypy/module/select/__init__.py", line 22, in Module
    from pypy.module.select.interp_epoll import public_symbols
   File "/src/pypy/pypy/module/select/interp_epoll.py", line 47, in <module>
    cconfig = rffi_platform.configure(CConfig)
   File "/src/pypy/rpython/rtyper/tool/rffi_platform.py", line 230, in configure
    ignore_errors=ignore_errors))
   File "/src/pypy/rpython/rtyper/tool/rffi_platform.py", line 746, in run_example_code
    output = build_executable_cache(files, eci, ignore_errors=ignore_errors)
   File "/src/pypy/rpython/tool/gcc_cache.py", line 28, in build_executable_cache
    result = platform.execute(platform.compile(c_files, eci))
   File "/src/pypy/rpython/translator/platform/__init__.py", line 54, in compile
    ofiles = self._compile_o_files(cfiles, eci, standalone)
   File "/src/pypy/rpython/translator/platform/__init__.py", line 76, in _compile_o_files
    ofiles.append(self._compile_c_file(self.cc, cfile, compile_args))
   File "/src/pypy/rpython/translator/platform/posix.py", line 41, in _compile_c_file
    cwd=str(cfile.dirpath()))
   File "/src/pypy/rpython/translator/platform/__init__.py", line 140, in _execute_c_compiler
    self._handle_error(returncode, stdout, stderr, outname)
   File "/src/pypy/rpython/translator/platform/__init__.py", line 152, in _handle_error
    raise CompilationError(stdout, stderr)
[translation:ERROR] CompilationError: CompilationError(err="""
	/src/usession-py3.5-0/platcheck_89.c: In function 'dump_section_EPOLL_CLOEXEC':
	/src/usession-py3.5-0/platcheck_89.c:270:7: error: 'EPOLL_CLOEXEC' undeclared (first use in this function)
	  if ((EPOLL_CLOEXEC) <= 0) {
	       ^~~~~~~~~~~~~
	/src/usession-py3.5-0/platcheck_89.c:270:7: note: each undeclared identifier is reported only once for each function it appears in
	""")
[translation] start debugger...
Traceback (most recent call last):
  File "rpython/bin/rpython", line 20, in <module>
> /src/pypy/rpython/translator/platform/__init__.py(152)_handle_error()
-> raise CompilationError(stdout, stderr)
    main()
  File "/src/pypy/rpython/translator/goal/translate.py", line 325, in main
    debug(True)
  File "/src/pypy/rpython/translator/goal/translate.py", line 278, in debug
    pdb_plus_show.start(tb)
  File "/src/pypy/rpython/translator/tool/pdbplus.py", line 442, in start
    fn(*args)
  File "/src/pypy/rpython/translator/tool/pdbplus.py", line 25, in post_mortem
    self.interaction(t.tb_frame, t)
  File "/opt/prefix/cpython-2.7/lib/python2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "/opt/prefix/cpython-2.7/lib/python2.7/cmd.py", line 109, in cmdloop
    self.preloop()
  File "/src/pypy/rpython/translator/tool/pdbplus.py", line 29, in preloop
    raise NoTTY("Cannot start the debugger when stdout is captured.")
rpython.translator.tool.pdbplus.NoTTY: Cannot start the debugger when stdout is captured.
```

**Comment by squeaky-pl** [comment]
From the man epoll

```
epoll_create1()
       If flags is 0, then, other than the fact that the obsolete size
       argument is dropped, epoll_create1() is the same as epoll_create().
       The following value can be included in flags to obtain different
       behavior:

       EPOLL_CLOEXEC
              Set the close-on-exec (FD_CLOEXEC) flag on the new file
              descriptor.  See the description of the O_CLOEXEC flag in
              open(2) for reasons why this may be useful.
```

and


```
epoll_create1() was added to the kernel in version 2.6.27.  Library
       support is provided in glibc starting with version 2.9.
```

Centos 5 has glibc 2.5. Probably for 3.5 and up I will need to support distributions not older from Centos 6 which has glibc 2.12. Not sure if PyPy2 should be also switched to Centos 6.

**Comment by squeaky-pl** [comment]
I made environment vars changes on master HEAD for the build to pass on "centos:centos6" image and 64 bit build.

If you want to build py3.5 branch:

1) Pull the repo to get the changes
2) Delete previous build artefacts by `sudo rm -rf src64 prefix64` inside `portable-pypy` dir
3) Edit `image/Dockerfile` and replace `FROM centos:centos5` with `FROM centos:centos6`
4) Proceed as before from scratch

**Comment by Bidski** [comment]
Unfortunately, I still receive errors.

```
[translation:info] Error:
   File "/src/pypy/rpython/translator/goal/translate.py", line 318, in main
    drv.proceed(goals)
   File "/src/pypy/rpython/translator/driver.py", line 551, in proceed
    result = self._execute(goals, task_skip = self._maybe_skip())
   File "/src/pypy/rpython/translator/tool/taskengine.py", line 114, in _execute
    res = self._do(goal, taskcallable, *args, **kwds)
   File "/src/pypy/rpython/translator/driver.py", line 278, in _do
    res = func()
   File "/src/pypy/rpython/translator/driver.py", line 315, in task_annotate
    s = annotator.build_types(self.entry_point, self.inputtypes)
   File "/src/pypy/rpython/annotator/annrpython.py", line 92, in build_types
    return self.build_graph_types(flowgraph, inputs_s, complete_now=complete_now)
   File "/src/pypy/rpython/annotator/annrpython.py", line 140, in build_graph_types
    self.complete()
   File "/src/pypy/rpython/annotator/annrpython.py", line 201, in complete
    self.complete_pending_blocks()
   File "/src/pypy/rpython/annotator/annrpython.py", line 196, in complete_pending_blocks
    self.processblock(graph, block)
   File "/src/pypy/rpython/annotator/annrpython.py", line 376, in processblock
    self.flowin(graph, block)
   File "/src/pypy/rpython/annotator/annrpython.py", line 550, in flowin
    self.follow_link(graph, link, constraints)
   File "/src/pypy/rpython/annotator/annrpython.py", line 585, in follow_link
    self.addpendingblock(graph, link.target, inputs_s)
   File "/src/pypy/rpython/annotator/annrpython.py", line 189, in addpendingblock
    self.mergeinputargs(graph, block, cells)
   File "/src/pypy/rpython/annotator/annrpython.py", line 413, in mergeinputargs
    unions = [annmodel.unionof(c1,c2) for c1, c2 in zip(oldcells,inputcells)]
   File "/src/pypy/rpython/annotator/model.py", line 775, in unionof
    s1 = pair(s1, s2).union()
   File "/src/pypy/rpython/annotator/binaryop.py", line 93, in union
    raise UnionError(obj1, obj2)
[translation:ERROR] UnionError: 

Offending annotations:
  SomeUnicodeString()
  SomeChar(const='?', no_nul=True)

In <FunctionGraph of (pypy.interpreter.function:536)Method.descr_method_repr at 0x7f4298548090>:
Happened at file /src/pypy/pypy/interpreter/function.py line 548

            objrepr = space.unicode_w(space.repr(self.w_instance))
            s = u'<bound method %s of %s>' % (name, objrepr)
            return space.wrap(s)

Processing block:
 block@115 is a <class 'rpython.flowspace.flowcontext.SpamBlock'> 
 in (pypy.interpreter.function:536)Method.descr_method_repr 
 containing the following operations: 
       v371 = getattr(v370, ('match')) 
       v372 = getattr(space_37, ('w_TypeError')) 
       v373 = simple_call(v371, space_37, v372) 
       v374 = bool(v373) 
 --end--
```

**Comment by squeaky-pl** [comment]
This is not related to portable builds. You need to chose a revision that translates or poke somebody on #pypy IRC channel to fix translation on py3.5 branch. Those branches are not even close to beta quality yet.

You can see here for example at the bottom that {linux64} py3.5  was failing translation on revision ` 89610:babebbeb4488   pypy-c-jit-linux-x86-64 [0, 1 F, 0 s, 0 x] (17 Jan)` which happens to be today. Note the exclamation mark in ` !  pypy-c-jit-linux-x86-64  "translation failed"`

Whilst one from yesterday translated successfully: `89597:31367d8c9631                       pypy-c-jit-linux-x86-64 [5538, 83 F, 1163 s, 4 x in 32m]`

So you can just translate revision `31367d8c9631` instead of tip of `py3.5` branch or wait until somebody fixes the tip.

http://buildbot.pypy.org/summary?builder=pypy-c-jit-linux-x86-64

**Comment by squeaky-pl** [comment]
patches apply cleanly to py3.5 branch now, given translation is not broken everything should be working now.
